# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [52]:
import numpy as np
d = np.random.normal(10,10,(4,7))
print(d)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        d[i][j] = (d[i][j] - mn) / (mx-mn)
print('\n',d)

[[17.18453647 30.9407627   7.58481247  6.05500801 13.00630852 21.96547861
  31.31249684]
 [ 3.66762476 -1.61781372 10.88180444 -0.89385945 13.26276171  3.36947233
  21.51681595]
 [29.04989412 -4.13386766  9.73595597 15.01022291  5.24987294 14.40837217
  22.19443151]
 [ 3.70122561 -6.64673845 -3.05162995 15.49929232 13.80131374 18.75726647
   4.44026514]]

 [[0.54666628 0.69740176 0.44147617 0.42471316 0.50088286 0.59905402
  0.70147508]
 [0.39855313 0.34063731 0.47760335 0.34857012 0.50369297 0.39528609
  0.59413775]
 [0.67668234 0.31306735 0.46504758 0.52284099 0.4158908  0.51624614
  0.6015628 ]
 [0.39892131 0.28553227 0.3249261  0.52820002 0.50959422 0.56389966
  0.40701942]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [82]:
d = np.random.randint(low=10,size=(8,10))
print(d,'\n')
mn = 10000
mni = 0
for i in range(8):
    if sum(d[i]) <= mn:
        mn = sum(d[i])
        mni = i
print(mn,mni,d[i])

[[2 9 9 6 2 5 6 5 6 0]
 [4 2 0 0 1 0 7 5 6 4]
 [8 1 2 7 6 4 8 1 2 3]
 [4 3 0 9 5 9 1 3 1 7]
 [5 4 7 8 9 7 0 4 3 9]
 [8 3 1 6 6 3 1 1 9 2]
 [1 1 4 0 4 1 1 2 2 9]
 [4 8 8 6 1 8 6 9 4 0]] 

25 6 [4 8 8 6 1 8 6 9 4 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [93]:
u = np.random.randint(low = 100, size=(1,2))[0]
v = np.random.randint(low = 100, size=(1,2))[0]
print(u,v)
print(((u[0]-v[0])**2 +(u[1]-v[1])**2)**0.5)

[44  6] [70 67]
66.30987860040162


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [103]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
#X = A-1*(-C) * B-1
X = np.linalg.inv(A) @ (-C) @  np.linalg.inv(B)
print(X)

[[ -7 -21]
 [-11  -8]
 [ -8  -4]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [254]:
d = np.loadtxt("minutes_n_ingredients.csv", dtype="int32",delimiter=",",skiprows=1)
print(d[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [255]:
a = d[:,1]
print("Срзнач", np.mean(a), "Мин", min(a), "Макс", max(a), "Медиана", np.median(a)) 
a = d[:,2]
print("Срзнач", np.mean(a), "Мин", min(a), "Макс", max(a), "Медиана", np.median(a))

Срзнач 21601.00169 Мин 0 Макс 2147483647 Медиана 40.0
Срзнач 9.05528 Мин 1 Макс 39 Медиана 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [278]:
q = np.quantile(a, 0.75)
d = d[d[:,1] <= q]
print(q)
print(d)

11.0
[[ 94746     10      6]
 [ 67660      5      6]
 [366174      7      9]
 ...
 [420725      5      3]
 [  4747      0      9]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [279]:
print("Кол-во рецептов с продолжительностью ноль",np.count_nonzero(d[:,1]==0))
d[:,1][d[:,1] == 0] = 1

Кол-во рецептов с продолжительностью ноль 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [280]:
print(len(np.unique(d,axis=0)))

12687


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [281]:
print(len(np.unique(d[:,2])))
print(np.unique(d[:,2]))

27
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 28 29]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [260]:
d2 = d[d[:,2]<= 5]
print(d2)

[[204134      5      3]
 [ 25623      6      4]
 [ 66842      2      4]
 ...
 [ 77371      6      3]
 [420725      5      3]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [261]:
sr = d[:,2] / d[:,1]
print(np.max(sr))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [276]:
d = np.loadtxt("minutes_n_ingredients.csv", dtype="int32",delimiter=",",skiprows=1)
sr100 = (d[d[:, 1].argsort()])[-100:]
print(sum(sr100[:,2]) / 100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [268]:
rows = np.random.randint(len(d), size=10)
print(d[rows,:])

[[164929     10      6]
 [  4657      1     11]
 [240394      4      7]
 [258932      5      5]
 [115685     10      6]
 [ 56203     10      5]
 [478941      5      5]
 [188187      5      4]
 [177260     10      6]
 [ 47435      9      5]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [275]:
d = np.loadtxt("minutes_n_ingredients.csv", dtype="int32",delimiter=",",skiprows=1)
av = np.mean(d[:,2])
k = len(d[:,2][d[:,2]< av])
print(k / len(d))

0.58802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [320]:
d = np.loadtxt("minutes_n_ingredients.csv", dtype="int32",delimiter=",",skiprows=1)
n1 = d[:,1] <= 20  
n2 = d[:,2]<=5
four = np.array(n1 * n2, int)
fourth = four[np.newaxis,:].T
d4 = d.copy()
d4 = np.append(d4, fourth, axis=1)
print(d4)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [329]:
print(np.sum(fourth)/ len(d) * 100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [8]:
d = np.loadtxt("minutes_n_ingredients.csv", dtype="int32",delimiter=",",skiprows=1)
a = d[d[:,1]  < 10]
b = d[((10 <= d[:,1] )*( d[:,1] < 20))]
c = d[d[:,1]  >= 20]
p = (min(len(a),len(b),len(c)))
f = np.zeros((3,p,3))

f[(0, np.arange(p), 0)] = a[:,0]
f[(0, np.arange(p), 1)] = a[:,1]
f[(0, np.arange(p), 2)] = a[:,2]

f[(1, np.arange(p), 0)] = b[:p,0]
f[(1, np.arange(p), 1)] = b[:p,1]
f[(1, np.arange(p), 2)] = b[:p,2]

f[(2, np.arange(p), 0)] = c[:p,0]
f[(2, np.arange(p), 1)] = c[:p,1]
f[(2, np.arange(p), 2)] = c[:p,2]
print(np.shape(f))

(3, 7588, 3)
